package com.cdrn.model;

public class Enums {
    public enum Role { CITIZEN, VOLUNTEER, AUTHORITY, ADMIN }
    public enum IncidentType { FLOOD, EARTHQUAKE, CYCLONE, FIRE, LANDSLIDE, MEDICAL, MISSING_PERSON, ROAD_BLOCKED, OTHER }
    public enum Severity { LOW, MEDIUM, HIGH, CRITICAL }
    public enum IncidentStatus { REPORTED, VERIFIED, IN_PROGRESS, RESOLVED, CLOSED }
    public enum AlertType { EARLY_WARNING, EVACUATION, SHELTER_INFO, ROAD_CLOSURE, ALL_CLEAR, ADVISORY }
    public enum DisasterType { FLOOD, EARTHQUAKE, CYCLONE, FIRE, LANDSLIDE, TSUNAMI, OTHER }
    public enum AlertSeverity { GREEN, YELLOW, ORANGE, RED }
    public enum ResourceType { FOOD, WATER, MEDICINE, BLANKET, CLOTHING, BLOOD, EQUIPMENT, VEHICLE, SHELTER_SPACE }
    public enum ResourceStatus { AVAILABLE, LOW, EXHAUSTED, REQUESTED }
    public enum ShelterType { RELIEF_CAMP, MEDICAL_CAMP, EVACUATION_CENTER, FOOD_DISTRIBUTION }
    public enum TaskType { RESCUE, MEDICAL_AID, FOOD_DISTRIBUTION, SEARCH, EVACUATION, ASSESSMENT, LOGISTICS }
    public enum TaskStatus { PENDING, ACCEPTED, IN_PROGRESS, COMPLETED, CANCELLED }
    public enum DamageCategory { RESIDENTIAL, COMMERCIAL, INFRASTRUCTURE, AGRICULTURAL, HUMAN_CASUALTY }
    public enum DamageStatus { SUBMITTED, UNDER_REVIEW, VERIFIED, APPROVED, REJECTED }
    public enum AssignmentStatus { ASSIGNED, ACTIVE, COMPLETED, WITHDRAWN }
    public enum NotificationType { ALERT, TASK_ASSIGNED, INCIDENT_UPDATE, SOS_RECEIVED, RESOURCE_LOW, SYSTEM }
}
